version: '3.8'

services:
  calibration:
    image: ghcr.io/tmolteno/tart_cal
    environment:
      TART_LOGIN_PW: sharkbait # used for pushing new gains to API. Match to set in the telescope API.
      TARGET: rhodes   # telescope API endpoint
      TART_NCAL: 3                                # use 1 for debugging only
      TART_CAL_ITERATIONS: 700
      TART_CAL_ELEVATION: 40
      TART_CAL_POINTING: 0
      TART_CAL_ARGS : "" 
      TART_CAL_INT: 15                            # Interval between measurements
      TART_UPLOAD: 1                            # Do the upload
    volumes:
      - ./calibration_results:/work
    command: /raw_calibrate.sh

