version: '3.8'

services:
  calibration:
    image: ghcr.io/tmolteno/tart_cal
    environment:
      TART_LOGIN_PW: sharkbait # used for pushing new gains to API. Match to set in the telescope API.
      TARGET: rhodes   # telescope API endpoint
      TART_NCAL: 2                                # use 1 for debugging only
      TART_CAL_INT: 10                            # Interval between measurements
      TART_UPLOAD: 1                            # Do the upload
    volumes:
      - ./calibration_results:/work
    command: /raw_calibrate.sh

